import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('sales_data.csv')
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month_name()
month_order = ['January','February','March','April','May','June','July','August','September','October','November','December']
top_products = df.groupby('Product')['Sales'].sum().sort_values(ascending=False)
plt.figure(figsize=(10,5))
plt.bar(top_products.index, top_products.values, color='steelblue')
plt.title('Top Products by Sales')
plt.savefig('chart1_products.png')
plt.show()
print('Chart 1 done!')
region_sales = df.groupby('Region')['Sales'].sum()
plt.figure(figsize=(7,7))
plt.pie(region_sales.values, labels=region_sales.index, autopct='%1.1f%%')
plt.title('Sales by Region')
plt.savefig('chart2_regions.png')
plt.show()
print('Chart 2 done!')
monthly = df.groupby('Month')['Sales'].sum().reindex(month_order).dropna()
plt.figure(figsize=(12,5))
plt.plot(monthly.index, monthly.values, marker='o', color='green', linewidth=2)
plt.title('Monthly Sales Trend')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('chart3_monthly.png')
plt.show()
print('Chart 3 done!')
category = df.groupby('Category')[['Sales','Profit']].sum()
x = range(len(category))
plt.figure(figsize=(8,5))
plt.bar([i-0.2 for i in x], category['Sales'], width=0.4, label='Sales', color='steelblue')
plt.bar([i+0.2 for i in x], category['Profit'], width=0.4, label='Profit', color='orange')
plt.xticks(x, category.index)
plt.title('Sales vs Profit by Category')
plt.legend()
plt.tight_layout()
plt.savefig('chart4_category.png')
plt.show()
print('All 4 charts done!')